### ISSUE TITLE
from moncli import MondayClient ERROR

### ISSUE THREAD

**Issue by aikanarov** [trix-solutions/moncli#27] opened 2020-02-10 20:23 UTC
Hi,

There is a problem importing moncli:

**from moncli import MondayClient**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-db0a5adeb7a0> in <module>
----> 1 from moncli import MondayClient

~/anaconda3/lib/python3.6/site-packages/moncli/__init__.py in <module>
----> 1 from .entities import MondayClient
      2 from .enums import *
      3 from .columnvalue import create_column_value

~/anaconda3/lib/python3.6/site-packages/moncli/entities/__init__.py in <module>
----> 1 from .client import MondayClient

~/anaconda3/lib/python3.6/site-packages/moncli/entities/client.py in <module>
----> 1 import moncli.entities.exceptions as ex
      2 from .. import api_v2 as client
      3 from ..enums import BoardKind, NotificationTargetType
      4 from .objects import MondayClientCredentials, Tag, Update, Notification
      5 from .board import Board

AttributeError: module 'moncli' has no attribute 'entities'

**Comment by Ashatz** [comment] 2020-03-20 01:25
Hello @aikanarov,

Unfortunately, I was not able to reproduce the bug.  Could you please send any additional information regarding your issue if possible.

Thank you!

**Comment by aikanarov** [comment] 2020-03-20 01:45
Hi,

Thank you very much for your response, i install moncli from command line:

```
(base) ubuntu@ip-172-31-81-216:~$ pip install moncli
Collecting moncli
  Downloading moncli-0.1.2-py3-none-any.whl (29 kB)
Requirement already satisfied: requests>=2.22.0 in ./anaconda3/lib/python3.6/site-packages (from moncli) (2.23.0)
Requirement already satisfied: nose>=1.3.7 in ./anaconda3/lib/python3.6/site-packages (from moncli) (1.3.7)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.22.0->moncli) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.22.0->moncli) (2.7)
Requirement already satisfied: chardet<4,>=3.0.2 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.22.0->moncli) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.22.0->moncli) (1.24.3)
Installing collected packages: moncli
Successfully installed moncli-0.1.2
```

And then i run from moncli import MondayClient and get this error.

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-db0a5adeb7a0> in <module>
----> 1 from moncli import MondayClient

~/anaconda3/lib/python3.6/site-packages/moncli/__init__.py in <module>
----> 1 from .entities import MondayClient
      2 from .enums import *
      3 from .columnvalue import create_column_value

~/anaconda3/lib/python3.6/site-packages/moncli/entities/__init__.py in <module>
----> 1 from .client import MondayClient

~/anaconda3/lib/python3.6/site-packages/moncli/entities/client.py in <module>
----> 1 import moncli.entities.exceptions as ex
      2 from .. import api_v2 as client
      3 from ..enums import BoardKind, NotificationTargetType
      4 from .objects import MondayClientCredentials, Tag, Update, Notification
      5 from .board import Board

AttributeError: module 'moncli' has no attribute 'entities'`

**Comment by Ashatz** [comment] 2020-03-20 01:50
@aikanarov, 

Thank you for your quick reply. I looked into your issue more, and it turns out I made a few import statements that are OK in Python 3.7+ but NOT for 3.6.  I have a working fix and am working on committing/deploying now.

**Comment by Ashatz** [comment] 2020-03-20 02:02
Hello @aikanarov 

I have deployed the fix.  You may download the latest package using the following command.
`
pip install --upgrade moncli
`

This should set you up with v0.1.4, which contains the import fix.  I am closing out this ticket. Please feel free to reach out if you run into any other issues!

**Closed by Ashatz** 2020-03-20 02:02 UTC
