### ISSUE TITLE
get_groups() doesn't finish executing

### ISSUE THREAD

**Issue by Vehemos** [trix-solutions/moncli#80] opened 2020-10-25 11:22 UTC
Hi, I was using get_groups() and even after waiting for 5 minutes the program didn't move on (I used the sample Monday "All in one software templates" to test). When using debugger I got:

> Evaluating: boards[0].get_groups() did not finish after 3.00s seconds.
> This may mean a number of things:
> - This evaluation is really slow and this is expected.
>     In this case it's possible to silence this error by raising the timeout, setting the
>     PYDEVD_WARN_EVALUATION_TIMEOUT environment variable to a bigger value.
> 
> - The evaluation may need other threads running while it's running:
>     In this case, it's possible to set the PYDEVD_UNBLOCK_THREADS_TIMEOUT
>     environment variable so that if after a given timeout an evaluation doesn't finish,
>     other threads are unblocked or you can manually resume all threads.
> 
>     Alternatively, it's also possible to skip breaking on a particular thread by setting a
>     `pydev_do_not_trace = True` attribute in the related threading.Thread instance
>     (if some thread should always be running and no breakpoints are expected to be hit in it).
> 
> - The evaluation is deadlocked:
>     In this case you may set the PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT
>     environment variable to true so that a thread dump is shown along with this message and
>     optionally, set the PYDEVD_INTERRUPT_THREAD_TIMEOUT to some value so that the debugger
>     tries to interrupt the evaluation (if possible) when this happens.

Which doesn't really tell anything we already don't know, here is the code which can be used to reproduce the issue:

> from moncli import MondayClient
> 
> client = MondayClient(user_name='XYZ@email.com', api_key_v1='', api_key_v2 ='INSERT_KEY_HERE')
> boards = client.get_boards(page=1, limit=50)
> 
> for every in boards:
>     print(every.get_groups())

**Expected Response:**
I would receive either the object containing the groups or an error

**Received Response:**
Infinite waiting loop

I would like to clarify that I didn't hit my Monday API rate limit.

Thank You

**Comment by Vehemos** [comment] 2020-10-25 11:31
Ok just did a little bit of testing, apparantly it gets stuck at:

Line 98 on https://github.com/trix-solutions/moncli/blob/master/moncli/entities/board.py
`            board = client.get_boards(
                self.__creds.api_key_v2,
                *field_list,
                ids=[int(self.id)])[0]`

Will update here once I get something more

**Comment by Vehemos** [comment] 2020-10-25 11:41
Apparantly I was able to receive the correct response as expected after editing line 90 on [board.py](https://github.com/trix-solutions/moncli/blob/master/moncli/entities/board.py)
 
from:
`        field_list = ['groups.id', 'groups.title', 'groups.items.id']`

to:
`        field_list = ['groups.id', 'groups.title']#, 'groups.items.id'] `

after removing the `groups.items.id` it is working as expected.
I am not sure why this is happeneing the way it is, can you please take a closer look?

Thank You

**Comment by Ashatz** [comment] 2020-10-25 21:44
Hello @Vehemos,

Thank you for bringing this to my attention.  From what you have reported, it does sound like you have have run into a query complexity issue.  

If you check out line 38 of https://github.com/trix-solutions/moncli/blob/master/moncli/api_v2/requests.py while you debug, please be sure that you are not getting a complexity error internally.  If you do, then the client waits 5 seconds before sending an additional request.  It takes about a minute for the complexity usage to restore itself back to normal.
https://monday.com/developers/v2#rate-limits-section

I will take a look, but please let me know if you find anything else.  Thanks!

**Comment by Ashatz** [comment] 2020-10-28 19:59
Hello @Vehemos,

Unfortunately I was unable to reproduce your issue.  With that being said, we just released v1 of Moncli this morning, which allows you to define return fields via the *args parameter.  I believe will address the issue that you brought up.  

I will be closing out this issue.  Please let me know if you run into any additional problems and happy coding!

**Closed by Ashatz** 2020-10-28 19:59 UTC
